# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = false

format = '''
$username$hostname$shell$directory$git_branch$git_commit$git_status$git_state$java$rust$gradle$character
'''

[shell]
format = "[$indicator](cyan) in "
disabled = false

[username]
show_always = false

[hostname]
ssh_only = true
# Setup options for git branch display
[git_branch]
symbol = "󰘬"
format = "on [$symbol:$branch](bold yellow) " #looks like "on 󰘬:main"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
error_symbol = "[✗❯](bold red)"
success_symbol = "[❯❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
